services:
  vr-control-postgres:
    container_name: vr-control-postgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:16.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./vr-control-postgres-data:/var/lib/postgresql/data
    networks:
      - vr-control-net

networks:
  vr-control-net:
    name: vr-control-net
    external: true